### ISSUE TITLE
Possibility to change the separator char, depending of locale

### ISSUE THREAD

**Issue by renenucci** [entronad/number_display#1]
According the country, the separator is dot (.) not comma (,), would be nice if we can set the locale tag and the library put the correct separator, or, at least, if we could put a literal separator char to use as parameter in 'createDisplay' method.

**Comment by entronad** [comment]
@renenucci 

Good idea!
I have added the feature to configure the separator and the digit units, please upgrade to 2.2.1 and have a try.
Details see the `separator` and 'units' property in README.

**Comment by sofierPoS** [comment]
we need a decimal separator as well as a group separator, e.g.
1,000.00
1.000,00

**Comment by entronad** [comment]
@sofierPoS 
Good suggestion.
I have added this feature to version 2.3.0, and pushed the code.
But for some special reason I can't access to pub.
So If you are eager to use this feature, just copy the lib/number_display.dart file in the repo to your project.

**Comment by entronad** [comment]
published version 2.3.0

**Comment by jalixdesign** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
DarthVagen, @StevenL2017, @jxpeng98, @RainmanGT, @uncleguanghui, @myywlc, @leapahea, @liulaojian, @threebowrice, @oddwatcher, @nhfmaster, @luckyuncle, @liweidong32768, @codingonion, @liyang85105, @wuyu9527, @iqgnat, @wmil, @kewangnet, @tuangeek, @861130245, @SSymbol, @JiaqiXiang-nb, @tianyikenan, @201708034122, @clientsfromhell, @gooyan, @zhaodc, @zhaozhiqiang, @dragonwong, @h4m5t, @congwang1998, @yichangle0410, @jaykon, @barry800414, @chenshipku, @nickattw, @qiubinglin, @Infi-zc, @wangyiqun1985, @ChatRichAi, @WangJinshans, @magnusguo, @xiaofeng9527, @ianmage, @CodeNeverStops, @lebin, @nerr, @2723070053, @IT-FE-Joshguggle241, @wufish, @Kylo-Cheok, @qpc, @JellyCCQ, @0a00, @sanluku, @abeibei12138, @LianLongBaGua, @Danielw0111, @turboyulin, @liuzhaoming5954, @T110E4, @nishiergouma, @chenyangnb1999, @uuuuuuuuuup, @sivan, @HalloEric, @Arealroookie, @suzhG, @Dear-enjoy, @lyran159, @OliverX2018, @TurkeyTeo, @shrimp0526, @J2oe, @whatever246, @mikamin, @ysj-1992, @JasonZhou404, @lihaoly, @lirunqi, @neptune1225, @Jstarr133, @mattshma, @junyihub, @CrazyDuck827, @joannanananana, @cfcfzzzz, @zh217, @VincentChandelier, @Blingtron4000, @WangMaoyuan, @fsy19960526, @chsiang426, @LogicDancing, @bbbcs, @cooliotseng, @TimothyZero, @MrFirePeak
